@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com",
  "password": "123"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123"
}

###

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "question 3",
  "content": "Teste de question 3"
}

###
# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}