@baseUrl = http://localhost:3333

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com",
  "password": "123"
}

###

POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123"
}